### ISSUE TITLE
bro

### ISSUE THREAD

**Issue by Been0s** [Oreofreakshake/RabbitDiscordBot#1]
miko masalaky miyai balaa varah bonda , balaa kudhu kohleemei rangalha veyheh 
-sincerely thage amaa-
![photo_2021-12-10_19-03-35](https://user-images.githubusercontent.com/85453011/148128183-c19867d2-1dde-4155-afae-bb638c540e6a.jpg)

**Comment by Oreofreakshake** [comment]
ok np bro, ezzz <3

**Comment by Been0s** [comment]
Damn fr

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
